### ISSUE TITLE
AssertionError: Over-read models\yolov3.weights

### ISSUE THREAD

**Issue by vijnasu** [jinyu121/DW2TF#12]
python main.py --cfg models\yolov3.cfg --weights models\yolov3.weights --output data\ --gpu 0

C:\Users\me\Documents\DW2TF\util\reader.py:31: RuntimeWarning: overflow encountered in long_scalars
  if ((major*10 + minor) >= 2 and major < 1000 and minor < 1000):
0 Tensor("yolov2/net1:0", shape=(?, 608, 608, 3), dtype=float32)
Traceback (most recent call last):
  File "main.py", line 112, in <module>
    main(args)
  File "main.py", line 53, in main
    parse_net(args.layers, args.cfg, args.weights, args.training)
  File "main.py", line 33, in parse_net
    training=training, const_inits=const_inits, verbose=verbose)
  File "C:\Users\me\Documents\DW2TF\util\cfg_layer.py", line 198, in get_cfg_layer
    layer = _cfg_layer_dict.get(layer_name, cfg_ignore)(B, H, W, C, net, param, weights_walker, stack, output_index, scope, training, const_inits, verbose)
  File "C:\Users\me\Documents\DW2TF\util\cfg_layer.py", line 52, in cfg_convolutional
    batch_normalize=batch_normalize)
  File "C:\Users\me\Documents\DW2TF\util\reader.py", line 64, in get_weight
    return self.get_weight_convolutional(**args)
  File "C:\Users\me\Documents\DW2TF\util\reader.py", line 55, in get_weight_convolutional
    biases = self.walk(filters)
  File "C:\Users\me\Documents\DW2TF\util\reader.py", line 41, in walk
    assert end_point <= self.size, 'Over-read {}'.format(self.path)
AssertionError: Over-read models\yolov3.weights

**Comment by sjain-stanford** [comment]
@vijnasu It seems like an [overflow issue](https://stackoverflow.com/questions/7559595/python-runtimewarning-overflow-encountered-in-long-scalars) on your machine when computing `major*10 + minor`. That is really odd, and I'm unable to reproduce this. Can you provide details of your platform (OS etc)? Have you tried running on a Linux instance?

**Comment by vijnasu** [comment]
@sjain-stanford I am using Intel NUC with i7 processor on Windows 10. Python 3.6 and TF 1.12 or 1.13 is in Anaconda. My requirement is on Windows.

**Comment by sjain-stanford** [comment]
@vijnasu At the moment it's difficult to reproduce this error on your environment. Please give it a try on Ubuntu. I've updated the README to reflect the dependencies on which the code is tested on.

**Comment by mohammedayub44** [comment]
@sjain-stanford 
I ran into this issue as well on Ubuntu 16.04 python version 3.6.6

**Comment by ROBYER1** [comment]
Same issue here, but I am using python 3.6 and Ubuntu 20.04

**Comment by puffdrum** [comment]
Same issue, using python 3.6 and Ubuntu18.04
