### ISSUE TITLE
minimal inference example with the TF model?

### ISSUE THREAD

**Issue by moabaom** [jinyu121/DW2TF#15]
Thanks for the repository. I manged to convert my weights to .pb and .ckpt files. However could you share or point to a link of an example inference using the models files ? just to see which tensor is the input/placeholder and which one are the outputs ?

**Comment by sjain-stanford** [comment]
@moabaom There are a few questions there, not exactly sure which you're asking. Here are some possible answers:

**To import / run the graph:**
You can import the graph using `tf.train.import_meta_graph`, initialize weights or load from checkpoint, and run it. See [this notebook](https://github.com/jinyu121/DW2TF/blob/master/docs/yolov2_dw2tf_validation.ipynb) with a snippet showing this.

**To visualize the graph:**
If you'd like to figure the input / output nodes, use [TensorBoard](https://www.tensorflow.org/guide/graph_viz) (comes packaged in the TensorFlow binary) to view the graph.

Closing this, feel free to re-open if you have further clarification / questions.

**Comment by noob-ja** [comment]
hi, so how exactly we read the output of the network?

for example, using yolov3-tiny, i feed in an image
the output of it is with shape (1,26,26,255)
![Screenshot from 2019-04-05 15-08-12](https://user-images.githubusercontent.com/17813529/55610020-abd36b00-57b4-11e9-91c3-af16d848adff.png)

whats the next step to get the predicted class and bounding box?
sry im new with this
