### ISSUE TITLE
How to read the output of the graph?

### ISSUE THREAD

**Issue by noob-ja** [jinyu121/DW2TF#16]
hi, so how exactly we read the output of the network?

for example, using yolov3-tiny, i feed in an image
the output of it is with shape (1,26,26,255)
![Screenshot from 2019-04-05 15-08-12](https://user-images.githubusercontent.com/17813529/55610126-dd4c3680-57b4-11e9-9a2b-94daa2f0a27d.png)

whats the next step to get the predicted class and bounding box?
sry im new with this

**Comment by noob-ja** [comment]
#15

**Comment by noob-ja** [comment]
im able to extract the output now, however, the result is not what i was expected

![person_detected](https://user-images.githubusercontent.com/17813529/55712676-c2322e80-5a21-11e9-9e2b-833ec185d55e.jpg)
![dog_detected](https://user-images.githubusercontent.com/17813529/55712729-d5dd9500-5a21-11e9-8c5a-5dd5c1432912.jpg)

it keeps detecting a lot of aeroplane and apples in every single photo i feed in

in the picture below, i have set the object threshold to be 0.7, yet it detected aeroplane and apples to be above even that
![zidane_detected](https://user-images.githubusercontent.com/17813529/55712749-e4c44780-5a21-11e9-95a7-3bf563d7f4d7.jpg)

**Comment by sjain-stanford** [comment]
@noob-ja - the purpose of DW2TF is to translate the convolutional layers in a network defined in darknet to TensorFlow. It is up to you to add the necessary post-processing (e.g. non-max suppression etc) to convert the features to the respective bounding box and class predictions. Sorry I couldn't be of help here.

**Comment by jinyu121** [comment]
@noob-ja 
After getting the output of the net, use non-max suppression (NMS) to select the "best" boxes. 
The pipeline in original YOLO code is "get the output of the net -> set a threshold to filter the boxes -> NMS". 
For the last image, may be the net is not well-trained? Or, you should adjust the clustering parameters before training.

**Comment by noob-ja** [comment]
i see, thx for the help :) really appreciate it

**Comment by kapil0kumar** [comment]
@noob-ja have you found the way to perform nms on the output?

**Comment by nishanthcgit** [comment]
@noob-ja sorry, I am quite new to TF, how did you get the bounding box coordinates from those output layers? I am aware of how to do nms etc but can't understand how you can convert the output layers into bboxes,classes and scores (apologies if this is a basic question)

**Comment by robinydv** [comment]
@kapil0kumar Hi, were you able to extract the bounding boxes from the output? I'm having some trouble with that.
