### ISSUE TITLE
What are the inputs and outputs layers names?

### ISSUE THREAD

**Issue by AbdeslemSmahi** [jinyu121/DW2TF#18]
I am trying to use the generated model in an Android application but it needs the input and output layers names.
where can i find those?

**Comment by sjain-stanford** [comment]
@AbdeslemSmahi One way is to import the graph into TensorBoard and look at the input/output node names.

**Comment by AbdeslemSmahi** [comment]
> @AbdeslemSmahi One way is to import the graph into TensorBoard and look at the input/output node names.

yes i managed to do that , Thank you.
