### ISSUE TITLE
yolo layers not shown on tensorboard graph?

### ISSUE THREAD

**Issue by chrisrapson** [jinyu121/DW2TF#29]
thanks for this tool. I was just wondering why the yolo layers don't show up when I convert a model and inspect it with tensorboard?
![tensorboard_graph](https://user-images.githubusercontent.com/4982550/62092145-4279e980-b2c8-11e9-9795-459e718e8391.png)

**Comment by sjain-stanford** [comment]
@chrisrapson The network description for yolo (in darknet) doesn't contain the post-processing layers for bounding box and class predictions. Hence they don't appear post conversion. Typically those nodes are added by your yolo validation wrapper, and do not hinder the conversion as they are not stateful (no weights to be converted).
