### ISSUE TITLE
tiny yolo v3 conversion

### ISSUE THREAD

**Issue by chrisrapson** [jinyu121/DW2TF#30]
When I use your tool to convert my cfg and weight files to tensorflow models, there seems to be an error. Here is the resulting graph from tensorboard, and I think that the connection down the right hand side should connect to a convolutional block, not a maxpool block. Specifically, convolutional5.
![tensorboard_graph](https://user-images.githubusercontent.com/4982550/62103184-c1cee380-b2ef-11e9-8466-9ca4d6bac1bb.png)

[AlexeyAB's explanation of route layers](https://github.com/AlexeyAB/darknet/issues/487#issuecomment-374902735) shows yolov2 has a similar connection to a convolutional block.

Also when I tried converting with [this similar repo](https://github.com/khanhhhh/tiny-yolo-tensorflow) it connects to a convolutional block.

I'm not 100% sure I've understood route blocks correctly, but it could be that you count the input `net1` as a block? If so, then you should increment the index (in this case from 8 to 9). Of course that only applies where the route has a positive number.

**Comment by sjain-stanford** [comment]
@chrisrapson Thanks for reporting this. Indeed, this is an indexing issue. The stack (in DW2TF) stores layers starting with `net` at index 0, whereas [@AlexeyAB's comment](https://github.com/AlexeyAB/darknet/issues/487#issuecomment-374902735) clarifies that indexing excludes the first net (placeholder). When route layers (basically concat operation) use relative indexing (negative values), this was not an issue (e.g. yolo-v2). However with absolute indexing (positive values), we're off by one layer. 

I've identified a simple fix, but need to verify it doesn't break other use-cases. Will push shortly. Let me know if you see any other issues. Thanks again!

**Comment by sjain-stanford** [comment]
I've fixed this by excluding `net` layer from the stack. Relative indices should work as usual. Absolute indexing starts with the first true layer. Below is the revised yolov3-tiny graph; route layer concatenates convolutional5 and not maxpool4. 

This fixes yolov3 and yolov3-tiny conversions, but has no impact on yolov2 (used relative indexing) or yolov2-tiny (no route layers). For those using DW2TF to convert yolov3 or yolov3-tiny, please use the latest release [DW2TF-1.2](https://github.com/jinyu121/DW2TF/releases/tag/v1.2).

@chrisrapson Closing this, please test and feel free to re-open if you see issues.

![image](https://user-images.githubusercontent.com/19234106/62157187-76054580-b2c1-11e9-9c47-3769ccceafc2.png)
