### ISSUE TITLE
ValueError: ''yolov3-tiny/'net1' is not a valid scope name

### ISSUE THREAD

**Issue by geneho** [jinyu121/DW2TF#35]
![image](https://user-images.githubusercontent.com/12985374/64318515-d38d6000-cfec-11e9-82b3-94fe86bc8b2c.png)

I'm currently training my images using yolov3-tiny.

The command i use is : 

> python main.py --cfg "C://Users//G//Desktop//ML//YOLO//DW2TF-master//DW2TF-master//data//yolov3-tiny-new.cfg" --weights "C://Users//G//Desktop//ML//YOLO//DW2TF-master//DW2TF-master//data//yolov3-tiny.weights" --output 'data//' --prefix 'yolov3-tiny/' --gpu 0

And which resulted in the error above. 

Please advice. Thanks!

**Comment by stingray91** [comment]
@sjain-stanford  do you have any ideas on this?  Thank you!

**Comment by AkkiSony** [comment]
I got a similar error. Can you please share me your ideas how to overcome this? @geneho

**Comment by geneho** [comment]
@AkkiSony  I cant remember how I solve this... Sorry... I did recall taking images to trim and label it 1 by 1...

**Comment by AkkiSony** [comment]
@geneho No worries! :) Thank you very much! I will look into it! :)
